interface Stock {
  symbol: string;
  name: string;
}

// A comprehensive list of major NSE stocks (e.g., components of NIFTY 200/500)
const NSE_STOCKS: Stock[] = [
  { symbol: 'ACC', name: 'ACC Ltd.' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises Ltd.' },
  { symbol: 'ADANIGREEN', name: 'Adani Green Energy Ltd.' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports and Special Economic Zone Ltd.' },
  { symbol: 'ADANIPOWER', name: 'Adani Power Ltd.' },
  { symbol: 'ADANITOTAL', name: 'Adani Total Gas Ltd.' },
  { symbol: 'ADANITRANS', name: 'Adani Transmission Ltd.' },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements Ltd.' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise Ltd.' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints Ltd.' },
  { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma Ltd.' },
  { symbol: 'AXISBANK', name: 'Axis Bank Ltd.' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto Ltd.' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd.' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance Ltd.' },
  { symbol: 'BALKRISIND', name: 'Balkrishna Industries Ltd.' },
  { symbol: 'BANDHANBNK', name: 'Bandhan Bank Ltd.' },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda' },
  { symbol: 'BEL', name: 'Bharat Electronics Ltd.' },
  { symbol: 'BERGEPAINT', name: 'Berger Paints India Ltd.' },
  { symbol: 'BHARATFORG', name: 'Bharat Forge Ltd.' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel Ltd.' },
  { symbol: 'BHEL', name: 'Bharat Heavy Electricals Ltd.' },
  { symbol: 'BIOCON', name: 'Biocon Ltd.' },
  { symbol: 'BOSCHLTD', name: 'Bosch Ltd.' },
  { symbol: 'BPCL', name: 'Bharat Petroleum Corporation Ltd.' },
  { symbol: 'BRITANNIA', name: 'Britannia Industries Ltd.' },
  { symbol: 'BSOFT', name: 'Birlasoft Ltd' },
  { symbol: 'CANBK', name: 'Canara Bank' },
  { symbol: 'CHOLAFIN', name: 'Cholamandalam Investment and Finance Company Ltd.' },
  { symbol: 'CIPLA', name: 'Cipla Ltd.' },
  { symbol: 'COALINDIA', name: 'Coal India Ltd.' },
  { symbol: 'COFORGE', name: 'Coforge Ltd.' },
  { symbol: 'COLPAL', name: 'Colgate-Palmolive (India) Ltd.' },
  { symbol: 'CONCOR', name: 'Container Corporation of India Ltd.' },
  { symbol: 'CUMMINSIND', name: 'Cummins India Ltd.' },
  { symbol: 'DABUR', name: 'Dabur India Ltd.' },
  { symbol: 'DALBHARAT', name: 'Dalmia Bharat Ltd.' },
  { symbol: 'DEEPAKNTR', name: 'Deepak Nitrite Ltd.' },
  { symbol: 'DIVISLAB', name: 'Divi\'s Laboratories Ltd.' },
  { symbol: 'DLF', name: 'DLF Ltd.' },
  { symbol: 'DRREDDY', name: 'Dr. Reddy\'s Laboratories Ltd.' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors Ltd.' },
  { symbol: 'ESCORTS', name: 'Escorts Kubota Ltd' },
  { symbol: 'EXIDEIND', name: 'Exide Industries Ltd.' },
  { symbol: 'FEDERALBNK', name: 'The Federal Bank Ltd.' },
  { symbol: 'GAIL', name: 'GAIL (India) Ltd.' },
  { symbol: 'GLENMARK', name: 'Glenmark Pharmaceuticals Ltd.' },
  { symbol: 'GMRINFRA', name: 'GMR Infrastructure Ltd.' },
  { symbol: 'GODREJCP', name: 'Godrej Consumer Products Ltd.' },
  { symbol: 'GODREJPROP', name: 'Godrej Properties Ltd.' },
  { symbol: 'GRASIM', name: 'Grasim Industries Ltd.' },
  { symbol: 'GUJGASLTD', name: 'Gujarat Gas Ltd.' },
  { symbol: 'HAL', name: 'Hindustan Aeronautics Ltd.' },
  { symbol: 'HAVELLS', name: 'Havells India Ltd.' },
  { symbol: 'HCLTECH', name: 'HCL Technologies Ltd.' },
  { symbol: 'HDFCAMC', name: 'HDFC Asset Management Company Ltd.' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank Ltd.' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance Company Ltd.' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp Ltd.' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries Ltd.' },
  { symbol: 'HINDCOPPER', name: 'Hindustan Copper Ltd.' },
  { symbol: 'HINDPETRO', name: 'Hindustan Petroleum Corporation Ltd.' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever Ltd.' },
  { symbol: 'HINDZINC', name: 'Hindustan Zinc Ltd.' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank Ltd.' },
  { symbol: 'ICICIGI', name: 'ICICI Lombard General Insurance Company Ltd.' },
  { symbol: 'ICICIPRULI', name: 'ICICI Prudential Life Insurance Company Ltd.' },
  { symbol: 'IDBI', name: 'IDBI Bank Ltd.' },
  { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank Ltd.' },
  { symbol: 'IEX', name: 'Indian Energy Exchange Ltd.' },
  { symbol: 'IGL', name: 'Indraprastha Gas Ltd.' },
  { symbol: 'INDHOTEL', name: 'The Indian Hotels Company Ltd.' },
  { symbol: 'INDIACEM', name: 'The India Cements Ltd.' },
  { symbol: 'INDIAMART', name: 'IndiaMART InterMESH Ltd.' },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation Ltd.' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank Ltd.' },
  { symbol: 'INDUSTOWER', name: 'Indus Towers Ltd.' },
  { symbol: 'INFY', name: 'Infosys Ltd.' },
  { symbol: 'IOC', name: 'Indian Oil Corporation Ltd.' },
  { symbol: 'IRCTC', name: 'Indian Railway Catering And Tourism Corporation Ltd.' },
  { symbol: 'ITC', name: 'ITC Ltd.' },
  { symbol: 'JINDALSTEL', name: 'Jindal Steel & Power Ltd.' },
  { symbol: 'JSWENERGY', name: 'JSW Energy Ltd.' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel Ltd.' },
  { symbol: 'JUBLFOOD', name: 'Jubilant FoodWorks Ltd.' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd.' },
  { symbol: 'L&TFH', name: 'L&T Finance Holdings Ltd.' },
  { symbol: 'LT', name: 'Larsen & Toubro Ltd.' },
  { symbol: 'LTI', name: 'Larsen & Toubro Infotech Ltd.' },
  { symbol: 'LTTS', name: 'L&T Technology Services Ltd.' },
  { symbol: 'LUPIN', name: 'Lupin Ltd.' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra Ltd.' },
  { symbol: 'M&MFIN', name: 'Mahindra & Mahindra Financial Services Ltd.' },
  { symbol: 'MANAPPURAM', name: 'Manappuram Finance Ltd.' },
  { symbol: 'MARICO', name: 'Marico Ltd.' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki India Ltd.' },
  { symbol: 'MCDOWELL-N', name: 'United Spirits Ltd.' },
  { symbol: 'MFSL', name: 'Max Financial Services Ltd.' },
  { symbol: 'MGL', name: 'Mahanagar Gas Ltd.' },
  { symbol: 'MOTHERSON', name: 'Motherson Sumi Systems Ltd.' },
  { symbol: 'MPHASIS', name: 'Mphasis Ltd.' },
  { symbol: 'MRF', name: 'MRF Ltd.' },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance Ltd.' },
  { symbol: 'NAUKRI', name: 'Info Edge (India) Ltd.' },
  { symbol: 'NAVINFLUOR', name: 'Navin Fluorine International Ltd.' },
  { symbol: 'NESTLEIND', name: 'Nestle India Ltd.' },
  { symbol: 'NMDC', name: 'NMDC Ltd.' },
  { symbol: 'NTPC', name: 'NTPC Ltd.' },
  { symbol: 'OBEROIRLTY', name: 'Oberoi Realty Ltd.' },
  { symbol: 'OFSS', name: 'Oracle Financial Services Software Ltd.' },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corporation Ltd.' },
  { symbol: 'PAGEIND', name: 'Page Industries Ltd.' },
  { symbol: 'PEL', name: 'Piramal Enterprises Ltd.' },
  { symbol: 'PETRONET', name: 'Petronet LNG Ltd.' },
  { symbol: 'PFC', name: 'Power Finance Corporation Ltd.' },
  { symbol: 'PFIZER', name: 'Pfizer Ltd.' },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries Ltd.' },
  { symbol: 'PIIND', name: 'PI Industries Ltd.' },
  { symbol: 'PNB', name: 'Punjab National Bank' },
  { symbol: 'POWERGRID', name: 'Power Grid Corporation of India Ltd.' },
  { symbol: 'PVR', name: 'PVR Ltd.' },
  { symbol: 'RAMCOCEM', name: 'The Ramco Cements Ltd.' },
  { symbol: 'RBLBANK', name: 'RBL Bank Ltd.' },
  { symbol: 'RECLTD', name: 'REC Ltd.' },
  { symbol: 'RELIANCE', name: 'Reliance Industries Ltd.' },
  { symbol: 'SAIL', name: 'Steel Authority of India Ltd.' },
  { symbol: 'SBICARD', name: 'SBI Cards and Payment Services Ltd.' },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance Company Ltd.' },
  { symbol: 'SBIN', name: 'State Bank of India' },
  { symbol: 'SHREECEM', name: 'Shree Cement Ltd.' },
  { symbol: 'SIEMENS', name: 'Siemens Ltd.' },
  { symbol: 'SRF', name: 'SRF Ltd.' },
  { symbol: 'SRTRANSFIN', name: 'Shriram Transport Finance Company Ltd.' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries Ltd.' },
  { symbol: 'SUNTV', name: 'Sun TV Network Ltd.' },
  { symbol: 'TATACHEM', name: 'Tata Chemicals Ltd.' },
  { symbol: 'TATACOMM', name: 'Tata Communications Ltd.' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products Ltd.' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors Ltd.' },
  { symbol: 'TATAPOWER', name: 'Tata Power Company Ltd.' },
  { symbol: 'TATASTEEL', name: 'Tata Steel Ltd.' },
  { symbol: 'TCS', name: 'Tata Consultancy Services Ltd.' },
  { symbol: 'TECHM', name: 'Tech Mahindra Ltd.' },
  { symbol: 'TITAN', name: 'Titan Company Ltd.' },
  { symbol: 'TORNTPHARM', name: 'Torrent Pharmaceuticals Ltd.' },
  { symbol: 'TRENT', name: 'Trent Ltd.' },
  { symbol: 'TVSMOTOR', name: 'TVS Motor Company Ltd.' },
  { symbol: 'UBL', name: 'United Breweries Ltd.' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement Ltd.' },
  { symbol: 'UPL', name: 'UPL Ltd.' },
  { symbol: 'VEDL', name: 'Vedanta Ltd.' },
  { symbol: 'VOLTAS', name: 'Voltas Ltd.' },
  { symbol: 'WIPRO', name: 'Wipro Ltd.' },
  { symbol: 'YESBANK', name: 'Yes Bank Ltd.' },
  { symbol: 'ZEEL', name: 'Zee Entertainment Enterprises Ltd.' },
  { symbol: 'ZOMATO', name: 'Zomato Ltd.' }
];

// A comprehensive list of major BSE stocks (e.g., components of S&P BSE 200/500)
const BSE_STOCKS: Stock[] = [
  { symbol: 'ABB', name: 'ABB India Ltd.' },
  { symbol: 'ACC', name: 'ACC Ltd.' },
  { symbol: 'AUBANK', name: 'AU Small Finance Bank Ltd.' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises Ltd.' },
  { symbol: 'ADANIGREEN', name: 'Adani Green Energy Ltd.' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports and Special Economic Zone Ltd.' },
  { symbol: 'ADANITRANS', name: 'Adani Transmission Ltd.' },
  { symbol: 'ALKEM', name: 'Alkem Laboratories Ltd.' },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements Ltd.' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise Ltd.' },
  { symbol: 'APOLLOTYRE', name: 'Apollo Tyres Ltd.' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints Ltd.' },
  { symbol: 'ASHOKLEY', name: 'Ashok Leyland Ltd.' },
  { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma Ltd.' },
  { symbol: 'DMART', name: 'Avenue Supermarts Ltd.' },
  { symbol: 'AXISBANK', name: 'Axis Bank Ltd.' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto Ltd.' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd.' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance Ltd.' },
  { symbol: 'BAJAJHLDNG', name: 'Bajaj Holdings & Investment Ltd.' },
  { symbol: 'BALKRISIND', name: 'Balkrishna Industries Ltd.' },
  { symbol: 'BANDHANBNK', name: 'Bandhan Bank Ltd.' },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda' },
  { symbol: 'BANKINDIA', name: 'Bank of India' },
  { symbol: 'BATAINDIA', name: 'Bata India Ltd.' },
  { symbol: 'BERGEPAINT', name: 'Berger Paints India Ltd.' },
  { symbol: 'BHARATFORG', name: 'Bharat Forge Ltd.' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel Ltd.' },
  { symbol: 'BHEL', name: 'Bharat Heavy Electricals Ltd.' },
  { symbol: 'BIOCON', name: 'Biocon Ltd.' },
  { symbol: 'BOSCHLTD', name: 'Bosch Ltd.' },
  { symbol: 'BPCL', name: 'Bharat Petroleum Corporation Ltd.' },
  { symbol: 'BRITANNIA', name: 'Britannia Industries Ltd.' },
  { symbol: 'CADILAHC', name: 'Cadila Healthcare Ltd.' },
  { symbol: 'CANBK', name: 'Canara Bank' },
  { symbol: 'CASTROLIND', name: 'Castrol India Ltd.' },
  { symbol: 'CHOLAFIN', name: 'Cholamandalam Investment and Finance Company Ltd.' },
  { symbol: 'CIPLA', name: 'Cipla Ltd.' },
  { symbol: 'COALINDIA', name: 'Coal India Ltd.' },
  { symbol: 'COFORGE', name: 'Coforge Ltd.' },
  { symbol: 'COLPAL', name: 'Colgate-Palmolive (India) Ltd.' },
  { symbol: 'CONCOR', name: 'Container Corporation of India Ltd.' },
  { symbol: 'CROMPTON', name: 'Crompton Greaves Consumer Electricals Ltd.' },
  { symbol: 'CUMMINSIND', name: 'Cummins India Ltd.' },
  { symbol: 'DABUR', name: 'Dabur India Ltd.' },
  { symbol: 'DALBHARAT', name: 'Dalmia Bharat Ltd.' },
  { symbol: 'DEEPAKNTR', name: 'Deepak Nitrite Ltd.' },
  { symbol: 'DIVISLAB', name: 'Divi\'s Laboratories Ltd.' },
  { symbol: 'DLF', name: 'DLF Ltd.' },
  { symbol: 'DRREDDY', name: 'Dr. Reddy\'s Laboratories Ltd.' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors Ltd.' },
  { symbol: 'EMAMILTD', name: 'Emami Ltd.' },
  { symbol: 'ESCORTS', name: 'Escorts Kubota Ltd.' },
  { symbol: 'EXIDEIND', name: 'Exide Industries Ltd.' },
  { symbol: 'FEDERALBNK', name: 'The Federal Bank Ltd.' },
  { symbol: 'FORTIS', name: 'Fortis Healthcare Ltd.' },
  { symbol: 'GAIL', name: 'GAIL (India) Ltd.' },
  { symbol: 'GLAND', name: 'Gland Pharma Ltd.' },
  { symbol: 'GLENMARK', name: 'Glenmark Pharmaceuticals Ltd.' },
  { symbol: 'GODREJCP', name: 'Godrej Consumer Products Ltd.' },
  { symbol: 'GODREJIND', name: 'Godrej Industries Ltd.' },
  { symbol: 'GODREJPROP', name: 'Godrej Properties Ltd.' },
  { symbol: 'GRASIM', name: 'Grasim Industries Ltd.' },
  { symbol: 'GSPL', name: 'Gujarat State Petronet Ltd.' },
  { symbol: 'HAVELLS', name: 'Havells India Ltd.' },
  { symbol: 'HCLTECH', name: 'HCL Technologies Ltd.' },
  { symbol: 'HDFCAMC', name: 'HDFC Asset Management Company Ltd.' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank Ltd.' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance Company Ltd.' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp Ltd.' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries Ltd.' },
  { symbol: 'HINDPETRO', name: 'Hindustan Petroleum Corporation Ltd.' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever Ltd.' },
  { symbol: 'HINDZINC', name: 'Hindustan Zinc Ltd.' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank Ltd.' },
  { symbol: 'ICICIGI', name: 'ICICI Lombard General Insurance Company Ltd.' },
  { symbol: 'ICICIPRULI', name: 'ICICI Prudential Life Insurance Company Ltd.' },
  { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank Ltd.' },
  { symbol: 'IBULHSGFIN', name: 'Indiabulls Housing Finance Ltd.' },
  { symbol: 'INDHOTEL', name: 'The Indian Hotels Company Ltd.' },
  { symbol: 'IOC', name: 'Indian Oil Corporation Ltd.' },
  { symbol: 'IRCTC', name: 'Indian Railway Catering And Tourism Corporation Ltd.' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank Ltd.' },
  { symbol: 'NAUKRI', name: 'Info Edge (India) Ltd.' },
  { symbol: 'INFY', name: 'Infosys Ltd.' },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation Ltd.' },
  { symbol: 'ITC', name: 'ITC Ltd.' },
  { symbol: 'JINDALSTEL', name: 'Jindal Steel & Power Ltd.' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel Ltd.' },
  { symbol: 'JUBLFOOD', name: 'Jubilant FoodWorks Ltd.' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd.' },
  { symbol: 'L&TFH', name: 'L&T Finance Holdings Ltd.' },
  { symbol: 'LT', name: 'Larsen & Toubro Ltd.' },
  { symbol: 'LTI', name: 'Larsen & Toubro Infotech Ltd.' },
  { symbol: 'LICHSGFIN', name: 'LIC Housing Finance Ltd.' },
  { symbol: 'LUPIN', name: 'Lupin Ltd.' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra Ltd.' },
  { symbol: 'M&MFIN', name: 'Mahindra & Mahindra Financial Services Ltd.' },
  { symbol: 'MANAPPURAM', name: 'Manappuram Finance Ltd.' },
  { symbol: 'MARICO', name: 'Marico Ltd.' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki India Ltd.' },
  { symbol: 'MFSL', name: 'Max Financial Services Ltd.' },
  { symbol: 'MOTHERSON', name: 'Motherson Sumi Systems Ltd.' },
  { symbol: 'MPHASIS', name: 'Mphasis Ltd.' },
  { symbol: 'MRF', name: 'MRF Ltd.' },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance Ltd.' },
  { symbol: 'NATIONALUM', name: 'National Aluminium Company Ltd.' },
  { symbol: 'NAVINFLUOR', name: 'Navin Fluorine International Ltd.' },
  { symbol: 'NESTLEIND', name: 'Nestle India Ltd.' },
  { symbol: 'NMDC', name: 'NMDC Ltd.' },
  { symbol: 'NTPC', name: 'NTPC Ltd.' },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corporation Ltd.' },
  { symbol: 'OFSS', name: 'Oracle Financial Services Software Ltd.' },
  { symbol: 'PAGEIND', name: 'Page Industries Ltd.' },
  { symbol: 'PETRONET', name: 'Petronet LNG Ltd.' },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries Ltd.' },
  { symbol: 'PEL', name: 'Piramal Enterprises Ltd.' },
  { symbol: 'PFC', name: 'Power Finance Corporation Ltd.' },
  { symbol: 'POWERGRID', name: 'Power Grid Corporation of India Ltd.' },
  { symbol: 'PNB', name: 'Punjab National Bank' },
  { symbol: 'RECLTD', name: 'REC Ltd.' },
  { symbol: 'RELIANCE', name: 'Reliance Industries Ltd.' },
  { symbol: 'SAIL', name: 'Steel Authority of India Ltd.' },
  { symbol: 'SBICARD', name: 'SBI Cards and Payment Services Ltd.' },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance Company Ltd.' },
  { symbol: 'SBIN', name: 'State Bank of India' },
  { symbol: 'SHREECEM', name: 'Shree Cement Ltd.' },
  { symbol: 'SRF', name: 'SRF Ltd.' },
  { symbol: 'SIEMENS', name: 'Siemens Ltd.' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries Ltd.' },
  { symbol: 'SUNTV', name: 'Sun TV Network Ltd.' },
  { symbol: 'TATACHEM', name: 'Tata Chemicals Ltd.' },
  { symbol: 'TATACOMM', name: 'Tata Communications Ltd.' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products Ltd.' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors Ltd.' },
  { symbol: 'TATAPOWER', name: 'Tata Power Company Ltd.' },
  { symbol: 'TATASTEEL', name: 'Tata Steel Ltd.' },
  { symbol: 'TCS', name: 'Tata Consultancy Services Ltd.' },
  { symbol: 'TECHM', name: 'Tech Mahindra Ltd.' },
  { symbol: 'TITAN', name: 'Titan Company Ltd.' },
  { symbol: 'TORNTPHARM', name: 'Torrent Pharmaceuticals Ltd.' },
  { symbol: 'TRENT', name: 'Trent Ltd.' },
  { symbol: 'UBL', name: 'United Breweries Ltd.' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement Ltd.' },
  { symbol: 'UNIONBANK', name: 'Union Bank of India' },
  { symbol: 'UPL', name: 'UPL Ltd.' },
  { symbol: 'VEDL', name: 'Vedanta Ltd.' },
  { symbol: 'VOLTAS', name: 'Voltas Ltd.' },
  { symbol: 'WIPRO', name: 'Wipro Ltd.' },
  { symbol: 'YESBANK', name: 'Yes Bank Ltd.' },
  { symbol: 'ZEEL', name: 'Zee Entertainment Enterprises Ltd.' }
];

export const getStockList = (exchange: 'NSE' | 'BSE'): Stock[] => {
  // Sort alphabetically by symbol for a better user experience in the dropdown
  const list = exchange === 'NSE' ? NSE_STOCKS : BSE_STOCKS;
  return list.sort((a, b) => a.symbol.localeCompare(b.symbol));
};
